version: 2.1

orbs:
    node: circleci/node@1.1
    aws-cli: circleci/aws-cli@1.4.0

defaults: &defaults
    docker:
        - image: "cimg/python:3.9.1"

jobs:
    build-deploy:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: yarn install
                      - run: yarn build

    deploy-to-eb:
        <<: *defaults
        steps:
            - aws-cli/setup:
                  aws-access-key-id: AWS_ACCESS_KEY_ID
                  aws-region: AWS_REGION
                  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            - run:
                  name: Deploying
                  command: eb deploy kormelonapi-env

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build-deploy:
                  filters:
                      branches:
                          only:
                              - circleci
                  context: kormelon

            - deploy-to-eb:
                  filters:
                      branches:
                          only:
                              - circleci
                  context: kormelon
