version: 2.1

orbs:
    node: circleci/node@5.0.1
    aws-cli: circleci/aws-cli@1.4.0
    aws-ebcli: circleci/aws-elastic-beanstalk@2.0.1

defaults: &defaults
    docker:
        - image: "cimg/python:3.9.1"

jobs:
    deploy-to-eb:
        <<: *defaults
        steps:
            - checkout
            - node/install:
                  node-version: "16.13"
                  install-yarn: true
            - restore_cache:
                key: cache-live-{{ checksum "yarn.lock" }}
            - run: yarn install
            - run: mkdir -p ./logs
            - run: yarn build
            - save_cache:
                key: cache-live-{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules
            - attach_workspace:
                  at: .
            - aws-ebcli/setup
            - aws-cli/setup:
                  aws-access-key-id: AWS_ACCESS_KEY_ID
                  aws-region: AWS_REGION
                  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            - run:
                  name: "Deploy to Elastic Beanstalk"
                  command: |
                      yarn generate-eb-zip
                      eb init kormelon-api-v2 --platform "Node.js 16" --region "ap-northeast-2"
                      eb deploy Kormelonapiv2-env

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - deploy-to-eb:
                  filters:
                      branches:
                          only:
                              - deploy
                  context: kormelon